services:
  - type: web
    name: giebee-erp
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: FLASK_SECRET_KEY
        value: 8dcd80847a420f609fe3c8aaf6a61d09
      - key: FLASK_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: giebee-db
          property: connectionString
    databases:
      - name: giebee-db
        databaseName: giebee_erp
        user: giebee_user
        postgresql: true
